"""initial schema per PRD §9.1

Revision ID: 84a75364f408
Revises: 
Create Date: 2026-04-27 13:37:17.740095

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a75364f408'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('context_rules', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('tone_variant', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ab_group', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('auth_provider', sa.Enum('google', 'yandex', 'magic_link', name='authprovider', native_enum=False, length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_tier', sa.Enum('free', 'solo', 'duo', 'family', name='subscriptiontier', native_enum=False, length=16), nullable=False),
    sa.Column('subscription_status', sa.Enum('none', 'trial', 'active', 'cancelled', 'grace', name='subscriptionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('subscription_source', sa.Enum('rustore', 'yookassa', 'sbp', 'appgallery', 'google_play', name='subscriptionsource', native_enum=False, length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('primary_platform', sa.Enum('android', 'web_only', name='platformkind', native_enum=False, length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_provider_user_id'), 'users', ['provider_user_id'], unique=False)
    op.create_table('anonymous_sessions',
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('birth_date_user', sa.Date(), nullable=False),
    sa.Column('birth_date_partner', sa.Date(), nullable=False),
    sa.Column('pair_mini_analysis', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('converted_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('platform_install', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['converted_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('device_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_type', sa.Enum('android', 'web', 'ios', name='devicetype', native_enum=False, length=16), nullable=False),
    sa.Column('push_token', sa.String(length=512), nullable=False),
    sa.Column('push_provider', sa.Enum('fcm', 'hms', 'web_push', name='pushprovider', native_enum=False, length=16), nullable=False),
    sa.Column('device_model', sa.String(length=120), nullable=True),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_registrations_user_id'), 'device_registrations', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('own', 'tracked', 'linked', name='profiletype', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_time', sa.String(length=8), nullable=True),
    sa.Column('birth_location', sa.String(length=255), nullable=True),
    sa.Column('relationship_type', sa.Enum('romantic_partner', 'close_person', name='relationshiptype', native_enum=False, length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profiles_one_own_per_user', 'profiles', ['owner_user_id'], unique=True, postgresql_where=sa.text("type = 'own'"))
    op.create_index(op.f('ix_profiles_owner_user_id'), 'profiles', ['owner_user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'solo', 'duo', 'family', name='subscriptiontier', native_enum=False, length=16), nullable=False),
    sa.Column('billing_period', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_provider', sa.Enum('rustore', 'yookassa', 'sbp', 'appgallery', 'google_play', name='subscriptionsource', native_enum=False, length=32), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_provider_subscription_id'), 'subscriptions', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('anonymous_session_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anonymous_session_id'], ['anonymous_sessions.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_anonymous_session_id'), 'events', ['anonymous_session_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('pair_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_a_id', sa.Uuid(), nullable=False),
    sa.Column('profile_b_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'separated', name='pairlinkstatus', native_enum=False, length=16), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('separated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pair_share_token', sa.String(length=64), nullable=True),
    sa.Column('snapshot_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_a_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_b_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_a_id', 'profile_b_id', name='uq_pair_links_profiles')
    )
    op.create_index(op.f('ix_pair_links_pair_share_token'), 'pair_links', ['pair_share_token'], unique=True)
    op.create_index(op.f('ix_pair_links_profile_a_id'), 'pair_links', ['profile_a_id'], unique=False)
    op.create_index(op.f('ix_pair_links_profile_b_id'), 'pair_links', ['profile_b_id'], unique=False)
    op.create_table('moment_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pair_link_id', sa.Uuid(), nullable=True),
    sa.Column('related_profile_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('conversation', 'decision', 'conflict', 'agreement', 'surprise', 'observation', name='momentcategory', native_enum=False, length=24), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('app', 'quick_tile', 'widget', name='momentsource', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pair_link_id'], ['pair_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moment_tags_occurred_at'), 'moment_tags', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_moment_tags_user_id'), 'moment_tags', ['user_id'], unique=False)
    op.create_table('pattern_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pair_link_id', sa.Uuid(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('reflections_count', sa.Integer(), nullable=False),
    sa.Column('moment_tags_count', sa.Integer(), nullable=False),
    sa.Column('patterns', sa.JSON(), nullable=False),
    sa.Column('ai_narrative', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pair_link_id'], ['pair_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_reports_user_id'), 'pattern_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_pattern_reports_week_start'), 'pattern_reports', ['week_start'], unique=False)
    op.create_table('reflections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pair_link_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=64), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_reaction', sa.Enum('positive', 'neutral', 'negative', name='userreaction', native_enum=False, length=16), nullable=True),
    sa.ForeignKeyConstraint(['pair_link_id'], ['pair_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflections_date'), 'reflections', ['date'], unique=False)
    op.create_index(op.f('ix_reflections_pair_link_id'), 'reflections', ['pair_link_id'], unique=False)
    op.create_index(op.f('ix_reflections_user_id'), 'reflections', ['user_id'], unique=False)
    op.create_table('ai_generation_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reflection_id', sa.Uuid(), nullable=True),
    sa.Column('pattern_report_id', sa.Uuid(), nullable=True),
    sa.Column('anonymous_session_token', sa.Uuid(), nullable=True),
    sa.Column('generation_type', sa.Enum('morning_prompt', 'evening_insight', 'pattern_report', 'wow_screen', name='generationtype', native_enum=False, length=32), nullable=False),
    sa.Column('system_prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_context', sa.JSON(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_reaction', sa.Enum('positive', 'neutral', 'negative', name='userreaction', native_enum=False, length=16), nullable=True),
    sa.Column('reaction_comment', sa.Text(), nullable=True),
    sa.Column('reaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anonymous_session_token'], ['anonymous_sessions.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pattern_report_id'], ['pattern_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_log_created_at'), 'ai_generation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_generation_log_generation_type'), 'ai_generation_log', ['generation_type'], unique=False)
    op.create_table('reflection_topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reflection_id', sa.Uuid(), nullable=False),
    sa.Column('topic_tags', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('extracted_concepts', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflection_topics_reflection_id'), 'reflection_topics', ['reflection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reflection_topics_reflection_id'), table_name='reflection_topics')
    op.drop_table('reflection_topics')
    op.drop_index(op.f('ix_ai_generation_log_generation_type'), table_name='ai_generation_log')
    op.drop_index(op.f('ix_ai_generation_log_created_at'), table_name='ai_generation_log')
    op.drop_table('ai_generation_log')
    op.drop_index(op.f('ix_reflections_user_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_pair_link_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_date'), table_name='reflections')
    op.drop_table('reflections')
    op.drop_index(op.f('ix_pattern_reports_week_start'), table_name='pattern_reports')
    op.drop_index(op.f('ix_pattern_reports_user_id'), table_name='pattern_reports')
    op.drop_table('pattern_reports')
    op.drop_index(op.f('ix_moment_tags_user_id'), table_name='moment_tags')
    op.drop_index(op.f('ix_moment_tags_occurred_at'), table_name='moment_tags')
    op.drop_table('moment_tags')
    op.drop_index(op.f('ix_pair_links_profile_b_id'), table_name='pair_links')
    op.drop_index(op.f('ix_pair_links_profile_a_id'), table_name='pair_links')
    op.drop_index(op.f('ix_pair_links_pair_share_token'), table_name='pair_links')
    op.drop_table('pair_links')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_anonymous_session_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_provider_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_profiles_owner_user_id'), table_name='profiles')
    op.drop_index('ix_profiles_one_own_per_user', table_name='profiles', postgresql_where=sa.text("type = 'own'"))
    op.drop_table('profiles')
    op.drop_index(op.f('ix_device_registrations_user_id'), table_name='device_registrations')
    op.drop_table('device_registrations')
    op.drop_table('anonymous_sessions')
    op.drop_index(op.f('ix_users_provider_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('prompts')
    # ### end Alembic commands ###
